import os
from openai import AzureOpenAI
import dotenv

dotenv.load_dotenv()
# Initialize the Azure OpenAI client with the specified parameters.
client = AzureOpenAI(
    azure_endpoint="https://hkust.azure-api.net",
    api_key=os.getenv("HKUST_AZURE_AI_API_KEY_PRIMARY"),
    api_version="2023-05-15"
)

def generateSummary(parsedString:str)->str:
      """
    Generate a summary for a financial article using a chat-based AI model.

    This function utilizes a chat-based AI model to generate a concise summary of the provided financial article.
    It sends a request to the AI model with the article content and receives a summarized response.

    Parameters:
    parsedString (str): A string containing the content of the financial article that needs to be summarized.

    Returns:
    str: A concise summary of the input financial article, as generated by the AI model.   
    """
    response = client.chat.completions.create(
        messages=[
            {
                "role": "assistant",
                "content": "You are a financial expert."
            },
            {
                "role": "user",
                "content": f"generate a summary for this financial article:\n{parsedString}"
            }
        ],
        model="gpt-4o",
    )
    return response.choices[0].message.content
